### ISSUE TITLE
start test demo failed with errors

### ISSUE THREAD

**Issue by Corgile** [google/federated-compute#4]
### System

win11

### python

3.10

### submitted command

```bat
bazelisk test //fcp/demo:federated_program_test
```

### error messages

```log
Repository rule http_archive defined at:
  C:/users/corgi/_bazel_corgi/hiuillts/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: repository @org_tensorflow' used the following cache hits instead of downloading the corresponding file.
 * Hash '99c732b92b1b37fc243a559e02f9aef5671771e272758aa4aec7f34dc92dac48' for https://github.com/tensorflow/tensorflow/archive/v2.11.0.tar.gz
If the definition of 'repository @org_tensorflow' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   Traceback (most recent call last):
        File "C:/users/corgi/_bazel_corgi/hiuillts/external/bazel_tools/tools/build_defs/repo/http.bzl", line 143, column 10, in _http_archive_impl
                patch(ctx, auth = auth)
        File "C:/users/corgi/_bazel_corgi/hiuillts/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 180, column 21, in patch
                fail("Error applying patch %s:\n%s%s" %
Error in fail: Error applying patch @//fcp/patches:tensorflow_googletest.patch:
The system cannot find the path specified.

ERROR: E:/workspace/repo/federated-compute/WORKSPACE:147:13: fetching http_archive rule //external:org_tensorflow: Traceback (most recent call last):
        File "C:/users/corgi/_bazel_corgi/hiuillts/external/bazel_tools/tools/build_defs/repo/http.bzl", line 143, column 10, in _http_archive_impl
                patch(ctx, auth = auth)
        File "C:/users/corgi/_bazel_corgi/hiuillts/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 180, column 21, in patch
                fail("Error applying patch %s:\n%s%s" %
Error in fail: Error applying patch @//fcp/patches:tensorflow_googletest.patch:
The system cannot find the path specified.

ERROR: Error computing the main repository mapping: no such package '@org_tensorflow//tensorflow': Error applying patch @//fcp/patches:tensorflow_googletest.patch:
The system cannot find the path specified.

Loading:

E:\WorkSpace\repo\federated-compute>
```

### related screenshot

![image](https://user-images.githubusercontent.com/48396880/227982338-d078fa0b-08db-437c-8774-53f2390cfc7a.png)

any ideas?😁

**Comment by timonvo** [comment]
We haven't tried building our project on a Windows machine, and I wouldn't be surprised if you'll hit various issues when you try to do so (in this particular case I believe bazel may be failing to find the "patch" binary we tell it to use, since Windows doesn't have it?). We don't plan to test or maintain our builds on Windows machines at this time, so I recommend building on a Linux machine instead (or in a Docker container running a Linux environment). I'll close this as "Not planned" accordingly.
